// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clientprefs.Database;

#nullable disable

namespace clientprefs.Migrations.MySQLMigrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20250106195441_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("clientprefs.Database.Table.Cookie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.ToTable("cookie", (string)null);
                });

            modelBuilder.Entity("clientprefs.Database.Table.UserCookie", b =>
                {
                    b.Property<ulong>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("account_id");

                    b.Property<int>("cookieId")
                        .HasColumnType("int")
                        .HasColumnName("cookie_id");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("accountId");

                    b.HasIndex("cookieId");

                    b.ToTable("user_cookie", (string)null);
                });

            modelBuilder.Entity("clientprefs.Database.Table.UserCookie", b =>
                {
                    b.HasOne("clientprefs.Database.Table.Cookie", "Cookie")
                        .WithMany()
                        .HasForeignKey("cookieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cookie");
                });
#pragma warning restore 612, 618
        }
    }
}
