// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using clientprefs.Database;

#nullable disable

namespace clientprefs.Migrations.NpgsqlMigrations
{
    [DbContext(typeof(NpgsqlContext))]
    partial class NpgsqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("clientprefs.Database.Table.Cookie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("id");

                    b.ToTable("cookie", (string)null);
                });

            modelBuilder.Entity("clientprefs.Database.Table.UserCookie", b =>
                {
                    b.Property<decimal>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("account_id");

                    b.Property<int>("cookieId")
                        .HasColumnType("integer")
                        .HasColumnName("cookie_id");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("accountId");

                    b.HasIndex("cookieId");

                    b.ToTable("user_cookie", (string)null);
                });

            modelBuilder.Entity("clientprefs.Database.Table.UserCookie", b =>
                {
                    b.HasOne("clientprefs.Database.Table.Cookie", "Cookie")
                        .WithMany()
                        .HasForeignKey("cookieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cookie");
                });
#pragma warning restore 612, 618
        }
    }
}
